### ISSUE TITLE
Consider setting a license for the published rules

### ISSUE THREAD

**Issue by Neo23x0** [avast/ioc#55]
I'm interested in incorporating your rule set into a new project, however, I noticed that you haven't specified a license for the published content. This implies that all copyright ownership remains with you, restricting the ability for others to use, share, or modify the rules without your consent. 

Would you consider adopting the Detection Rule License (DRL) for the rules published in this repository?

https://github.com/SigmaHQ/Detection-Rule-License

**Comment by avast-ti** [comment]
Done, our repository is under the DRL licence now.
Thank you.

**Comment by Neo23x0** [comment]
Added to : https://github.com/YARAHQ/yara-forge/pull/3
